apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: dev-team
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "10"
    limits.memory: 16Gi


---

From the above taml file;
* All pods in the dev-team namespace can request up to 4 CPU cores and 8Gi memory.

* They can use limit up to 10 CPU cores and 16Gi memory.
