apiVersion: v1
kind: Pod
metadata:
  name: quota-example
  namespace: dev-team
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "1"
          memory: "512Mi"
        limits:
          cpu: "2"
          memory: "1Gi"


----


* The above YAML defines a Pod named quota-example in the dev-team namespace. It runs a single container using the busybox image, executing the sleep 3600 command to keep the pod running for an hour. The container requests 1 CPU and 512Mi of memory, with limits set to 2 CPUs and 1Gi of memory. This ensures the pod has guaranteed minimum resources while capping its maximum usage.











