apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-quota
  namespace: staging
spec:
  hard:
    requests.storage: 100Gi
    persistentvolumeclaims: "10"


---


From the above yaml file;
* PVCs in staging namespace can request up to 100Gi total storage utilization

* Max 10 PVCs allowed.
