apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
spec:
  containers:
    - name: demo-container
      image: busybox
      command: ["sh", "-c", "echo 'Username:' && cat /etc/secrets/username && echo 'Password:' && cat /etc/secrets/password && sleep 3600"]
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
