apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: dev
spec:
  containers:
    - name: nginx
      image: nginxi


---

* (OR) We can set namespace while applying :-
      
                  kubectl apply -f pod-sample-NS.yaml -n dev
