apiVersion: v1
kind: Namespace
metadata:
  name: devops-ns
  labels:                       # Labels are key-value pairs (Metadata)
    team: DevopsTeam

---

* From the above yaml file the name of the namespace will be “devops-ns” and the key-value pair will be “team: DevopsTeam”
