apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-replica
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkinspod
          image: jenkins/jenkins:lts  
